version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: coingecko-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  coingecko-harvester:
    build: .
    container_name: coingecko-harvester
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - CG_KEY=${CG_KEY}
      - PBI_PRICES_PUSH_URL=${PBI_PRICES_PUSH_URL}
      - PBI_EXCHANGE_RATES_URL=${PBI_EXCHANGE_RATES_URL}
      - PBI_COMPANIES_URL=${PBI_COMPANIES_URL}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"